version: '2'

services:

  result:
    build: .
    ports:
      - "5001:80"
      - "5858:5858"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - front-tier
      - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "./:/app"
      - "./healthchecks:/healthchecks"
    networks:
      - back-tier
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"

  # TODO: seed data, w/o using the voting api, which is what the mono repo does

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
